bcp stock_dbase..DM_DRAWING out  week_bcp\DM_DRAWING.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..DM_ITEMS_DETAILS out  week_bcp\DM_ITEMS_DETAILS.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..DM_ORDER_CALC out  week_bcp\DM_ORDER_CALC.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..DM_ORDER_FINAL out  week_bcp\DM_ORDER_FINAL.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..DM_ORDER_IC out  week_bcp\DM_ORDER_IC.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..DM_ORDER_ITEMS_IC out  week_bcp\DM_ORDER_ITEMS_IC.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..DM_ORDER_STATES out  week_bcp\DM_ORDER_STATES.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..DM_ORDER_TYPE out  week_bcp\DM_ORDER_TYPE.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..DM_PROOF_RECEIPT out  week_bcp\DM_PROOF_RECEIPT.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..DM_SER_PROFILE out  week_bcp\DM_SER_PROFILE.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..DM_SETTING out  week_bcp\DM_SETTING.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..DM_STATE_TYPES out  week_bcp\DM_STATE_TYPES.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..MM_ALTERNATIVES out  week_bcp\MM_ALTERNATIVES.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..MM_DEPT_CONS out  week_bcp\MM_DEPT_CONS.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..MM_DEPT_GROUPS out  week_bcp\MM_DEPT_GROUPS.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..MM_DEPT_ITMS out  week_bcp\MM_DEPT_ITMS.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..MM_MC_DEPT_QTY out  week_bcp\MM_MC_DEPT_QTY.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..PM_ORDER out  week_bcp\PM_ORDER.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..PM_ORDER_ITEMS out  week_bcp\PM_ORDER_ITEMS.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..PM_ORDER_ITEMS_CALC out  week_bcp\PM_ORDER_ITEMS_CALC.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..PM_ORDER_ITEMS_OFFERS out  week_bcp\PM_ORDER_ITEMS_OFFERS.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_COMPLAINT out  week_bcp\SCM_COMPLAINT.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_DEPT_MASTER out  week_bcp\SCM_DEPT_MASTER.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_FACT out  week_bcp\SCM_FACT.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_FACT_DEPT out  week_bcp\SCM_FACT_DEPT.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_FACT_DEPT2 out  week_bcp\SCM_FACT_DEPT2.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_IMPORTER out  week_bcp\SCM_IMPORTER.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_INCOMING_NOTES out  week_bcp\SCM_INCOMING_NOTES.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_ITEMS_MASTER out  week_bcp\SCM_ITEMS_MASTER.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_MAIN_DEPT out  week_bcp\SCM_MAIN_DEPT.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_MESSAGE_CODE out  week_bcp\SCM_MESSAGE_CODE.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_MOWAZNA out  week_bcp\SCM_MOWAZNA.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_MOWZNA_ITEMS out  week_bcp\SCM_MOWZNA_ITEMS.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_OFFERS out  week_bcp\SCM_OFFERS.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_PROJECTS out  week_bcp\SCM_PROJECTS.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_SAVE_FILES out  week_bcp\SCM_SAVE_FILES.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_SUPPLIERS out  week_bcp\SCM_SUPPLIERS.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_SYSTEM_TABLE out  week_bcp\SCM_SYSTEM_TABLE.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_TRANSACTIONS_CODES out  week_bcp\SCM_TRANSACTIONS_CODES.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_USERS out  week_bcp\SCM_USERS.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM__ACCOUNT_CENTER_C out  week_bcp\SCM__ACCOUNT_CENTER_C.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SOM_DM_IC out  week_bcp\SOM_DM_IC.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SOM_IC out  week_bcp\SOM_IC.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SOM_ITEMS_IC out  week_bcp\SOM_ITEMS_IC.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SOM_TYPES out  week_bcp\SOM_TYPES.txt   -Usa -P -Squsfactory -c
