bcp stock_dbase..DM_DRAWING out  bcp2\DM_DRAWING.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..DM_ITEMS_DETAILS out  bcp2\DM_ITEMS_DETAILS.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..DM_ORDER_CALC out  bcp2\DM_ORDER_CALC.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..DM_ORDER_FINAL out  bcp2\DM_ORDER_FINAL.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..DM_ORDER_IC out  bcp2\DM_ORDER_IC.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..DM_ORDER_ITEMS_IC out  bcp2\DM_ORDER_ITEMS_IC.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..DM_ORDER_STATES out  bcp2\DM_ORDER_STATES.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..DM_ORDER_TYPE out  bcp2\DM_ORDER_TYPE.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..DM_PROOF_RECEIPT out  bcp2\DM_PROOF_RECEIPT.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..DM_SER_PROFILE out  bcp2\DM_SER_PROFILE.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..DM_SETTING out  bcp2\DM_SETTING.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..DM_STATE_TYPES out  bcp2\DM_STATE_TYPES.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..MM_ALTERNATIVES out  bcp2\MM_ALTERNATIVES.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..MM_DEPT_CONS out  bcp2\MM_DEPT_CONS.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..MM_DEPT_GROUPS out  bcp2\MM_DEPT_GROUPS.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..MM_DEPT_ITMS out  bcp2\MM_DEPT_ITMS.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..MM_MC_DEPT_QTY out  bcp2\MM_MC_DEPT_QTY.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..PM_ORDER out  bcp2\PM_ORDER.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..PM_ORDER_ITEMS out  bcp2\PM_ORDER_ITEMS.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..PM_ORDER_ITEMS_CALC out  bcp2\PM_ORDER_ITEMS_CALC.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..PM_ORDER_ITEMS_OFFERS out  bcp2\PM_ORDER_ITEMS_OFFERS.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_COMPLAINT out  bcp2\SCM_COMPLAINT.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_DEPT_MASTER out  bcp2\SCM_DEPT_MASTER.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_FACT out  bcp2\SCM_FACT.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_FACT_DEPT out  bcp2\SCM_FACT_DEPT.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_FACT_DEPT2 out  bcp2\SCM_FACT_DEPT2.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_IMPORTER out  bcp2\SCM_IMPORTER.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_INCOMING_NOTES out  bcp2\SCM_INCOMING_NOTES.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_ITEMS_MASTER out  bcp2\SCM_ITEMS_MASTER.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_MAIN_DEPT out  bcp2\SCM_MAIN_DEPT.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_MESSAGE_CODE out  bcp2\SCM_MESSAGE_CODE.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_MOWAZNA out  bcp2\SCM_MOWAZNA.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_MOWZNA_ITEMS out  bcp2\SCM_MOWZNA_ITEMS.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_OFFERS out  bcp2\SCM_OFFERS.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_PROJECTS out  bcp2\SCM_PROJECTS.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_SAVE_FILES out  bcp2\SCM_SAVE_FILES.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_SUPPLIERS out  bcp2\SCM_SUPPLIERS.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_SYSTEM_TABLE out  bcp2\SCM_SYSTEM_TABLE.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_TRANSACTIONS_CODES out  bcp2\SCM_TRANSACTIONS_CODES.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM_USERS out  bcp2\SCM_USERS.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SCM__ACCOUNT_CENTER_C out  bcp2\SCM__ACCOUNT_CENTER_C.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SOM_DM_IC out  bcp2\SOM_DM_IC.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SOM_IC out  bcp2\SOM_IC.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SOM_ITEMS_IC out  bcp2\SOM_ITEMS_IC.txt   -Usa -P -Squsfactory -c
bcp stock_dbase..SOM_TYPES out  bcp2\SOM_TYPES.txt   -Usa -P -Squsfactory -c
